import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createApp, amountInCents, paymentState} from '../server.js';
import {cieloClient} from '../cielo.js';
const password='test-only-password-123456789';
async function fixture(t,provider,mode='demo') {
 const {app,db}=createApp({ADMIN_PASSWORD:password,PAYMENT_MODE:mode,PUBLIC_URL:'http://localhost:3000',DB_PATH:':memory:',CIELO_MERCHANT_ID:'test',CIELO_MERCHANT_KEY:'test',CIELO_SOP_CLIENT_ID:'test',CIELO_SOP_CLIENT_SECRET:'test'},provider);
 const server=app.listen(0,'127.0.0.1'); await new Promise(r=>server.once('listening',r));
 t.after(()=>{server.closeAllConnections();server.close();db.close();});
 const base=`http://127.0.0.1:${server.address().port}`;
 let cookie='';
 async function request(path,body,extra={}){return fetch(base+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json','X-Essencia-Request':'1',Origin:'http://localhost:3000',Cookie:cookie,...extra},...(body===undefined?{}:{body:JSON.stringify(body)})});}
 const login=await request('/api/login',{password});cookie=login.headers.get('set-cookie').split(';')[0];
 async function create(extra={}){const r=await request('/api/invoices',{name:'Doador Teste',email:'teste@example.com',description:'Apoio à ONG',amount:'125,90',dueDate:new Date(Date.now()+86400000).toISOString().slice(0,10),requestKey:randomUUID(),...extra});return {response:r,invoice:await r.json()};}
 return {request,create,db,base};
}
test('valores monetários são exatos e rejeitam entradas ambíguas',()=>{assert.equal(amountInCents('125,90'),12590);assert.equal(amountInCents('1.1'),110);for(const v of ['0','-5','1e3','1.234,56','NaN','100000.01',1,null])assert.throws(()=>amountInCents(v));assert.equal(paymentState(1),'authorized');assert.equal(paymentState(2),'paid');assert.equal(paymentState(12),'review');});
test('proteção de sessão, origem e dados privados',async t=>{const f=await fixture(t);assert.equal((await fetch(f.base+'/api/invoices')).status,401);assert.equal((await f.request('/api/invoices',{}, {Origin:'https://evil.test'})).status,403);const {invoice}=await f.create();const publicData=await (await f.request('/api/public/'+invoice.id)).json();assert.equal(publicData.name,undefined);assert.equal(publicData.email,undefined);assert.equal(publicData.orderId,undefined);await f.request('/api/logout',{});assert.equal((await f.request('/api/invoices')).status,401);});
test('criação idempotente e pagamento demo único mesmo em concorrência',async t=>{const f=await fixture(t);const requestKey=randomUUID();const a=await f.create({requestKey});const b=await f.create({requestKey});assert.equal(a.invoice.id,b.invoice.id);const results=await Promise.all([f.request(`/api/public/${a.invoice.id}/pay`,{demo:true}),f.request(`/api/public/${a.invoice.id}/pay`,{demo:true})]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);assert.equal((await (await f.request('/api/public/'+a.invoice.id)).json()).state,'paid');});
test('expiração e rejeição de cartão bruto ou alteração de valor',async t=>{const f=await fixture(t);const {invoice}=await f.create();assert.equal((await f.request(`/api/public/${invoice.id}/pay`,{demo:true,amount:1})).status,400);assert.equal((await f.request(`/api/public/${invoice.id}/pay`,{demo:true,CardNumber:'4111111111111111'})).status,400);f.db.prepare('UPDATE invoices SET expires_at=? WHERE id=?').run('2020-01-01T00:00:00Z',invoice.id);assert.equal((await f.request(`/api/public/${invoice.id}/pay`,{demo:true})).status,409);assert.equal((await (await f.request('/api/public/'+invoice.id)).json()).state,'expired');});
test('falha incerta bloqueia novas tentativas e concilia pelo pedido',async t=>{let calls=0,order;const paymentId=randomUUID();const f=await fixture(t,{async create(i){calls++;order=i;throw new Error('timeout');},async find(id){assert.equal(id,order.order_id);return {Payments:[{PaymentId:paymentId}]};},async query(){return {MerchantOrderId:order.order_id,Payment:{PaymentId:paymentId,Amount:order.amount,Type:'CreditCard',Status:2}};}},'sandbox');const {invoice}=await f.create();const path=`/api/public/${invoice.id}/pay`;const body={paymentToken:randomUUID(),brand:'Visa'};assert.equal((await f.request(path,body)).status,202);assert.equal((await f.request(path,body)).status,409);assert.equal(calls,1);const result=await (await f.request(`/api/invoices/${invoice.id}/refresh`,{})).json();assert.equal(result.state,'paid');});
test('resposta divergente não confirma pagamento',async t=>{const f=await fixture(t,{async create(i){return {MerchantOrderId:i.order_id,Payment:{PaymentId:randomUUID(),Amount:1,Type:'CreditCard',Status:2}};}},'sandbox');const {invoice}=await f.create();const result=await (await f.request(`/api/public/${invoice.id}/pay`,{paymentToken:randomUUID(),brand:'Visa'})).json();assert.equal(result.state,'review');});
test('autorização sem captura não é tratada como paga',async t=>{const f=await fixture(t,{async create(i){return {MerchantOrderId:i.order_id,Payment:{PaymentId:randomUUID(),Amount:i.amount,Type:'CreditCard',Status:1}};}},'sandbox');const {invoice}=await f.create();const result=await (await f.request(`/api/public/${invoice.id}/pay`,{paymentToken:randomUUID(),brand:'Master'})).json();assert.equal(result.state,'authorized');});
test('produção exige HTTPS, ativação e credenciais completas',()=>{assert.throws(()=>createApp({ADMIN_PASSWORD:password,PAYMENT_MODE:'production',DB_PATH:':memory:'}));assert.throws(()=>createApp({ADMIN_PASSWORD:password,PAYMENT_MODE:'sandbox',DB_PATH:':memory:'}));});
test('adaptador usa token e valor persistido nos endpoints oficiais',async()=>{const requests=[];const client=cieloClient({PAYMENT_MODE:'sandbox',CIELO_MERCHANT_ID:'merchant',CIELO_MERCHANT_KEY:'secret',CIELO_SOP_CLIENT_ID:'id',CIELO_SOP_CLIENT_SECRET:'secret'},async(url,options)=>{requests.push({url,options});return {ok:true,json:async()=>url.includes('oauth2')?{access_token:'oauth'}:url.includes('accesstoken')?{AccessToken:'sop'}:{}};});assert.equal((await client.sop()).accessToken,'sop');await client.create({order_id:'abc',amount:15000,name:'Teste'},'token','Visa');await client.query('payment');const sale=requests[2];assert.equal(sale.url,'https://apisandbox.cieloecommerce.cielo.com.br/v2/sales/');const body=JSON.parse(sale.options.body);assert.equal(body.Payment.Amount,15000);assert.equal(body.Payment.Capture,true);assert.deepEqual(body.Payment.CreditCard,{PaymentToken:'token',Brand:'Visa'});assert.match(requests[3].url,/apiquerysandbox/);});
