import {chromium} from '@playwright/test';
import {createApp} from '../server.js';
import {mkdirSync} from 'node:fs';
import assert from 'node:assert/strict';
const {app,db}=createApp({ADMIN_PASSWORD:'ui-test-password-only-123',PAYMENT_MODE:'demo',PUBLIC_URL:'http://localhost:3107',DB_PATH:':memory:'});
const server=app.listen(3107,'127.0.0.1');await new Promise(r=>server.once('listening',r));
const browser=await chromium.launch({headless:true,...(process.env.UI_BROWSER_CHANNEL?{channel:process.env.UI_BROWSER_CHANNEL}:{})});
try {
 const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:3107');await page.locator('[name=password]').fill('ui-test-password-only-123');await page.getByRole('button',{name:/Entrar no painel/}).click();await page.locator('#dashboard').waitFor({state:'visible'});
 await page.getByRole('button',{name:'＋ Nova cobrança'}).click();await page.locator('[name=name]').fill('Doador de demonstração');await page.locator('[name=amount]').fill('150,00');await page.locator('[name=description]').fill('Apoio às atividades da Essência Viva');await page.locator('#create-submit').click();await page.locator('#share-dialog').waitFor({state:'visible'});const url=await page.locator('#share-link').inputValue();assert.match(url,/localhost:3107\/p\//);await page.locator('#close-share').click();
 mkdirSync('.preview',{recursive:true});await page.screenshot({path:'.preview/dashboard.png',fullPage:true});
 const donor=await browser.newPage({viewport:{width:1280,height:900}});await donor.goto(url);await donor.getByRole('button',{name:'Simular doação'}).waitFor({state:'visible'});assert.equal(await donor.locator('#amount').textContent(),'R$ 150,00');await donor.screenshot({path:'.preview/checkout.png',fullPage:true});
 await donor.setViewportSize({width:390,height:844});await donor.screenshot({path:'.preview/mobile.png',fullPage:true});assert.equal(await donor.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await donor.getByRole('button',{name:'Simular doação'}).click();await donor.getByText('Doação simulada com sucesso! Nenhuma cobrança foi realizada.').waitFor();await donor.reload();await donor.getByText('Doação simulada com sucesso! Nenhuma cobrança foi realizada.').waitFor();assert.equal(await donor.locator('#pay-form').isVisible(),false);
 await page.locator('#reload').click();await page.getByText('Paga',{exact:true}).waitFor();assert.equal(await page.locator('#total-paid').textContent(),'R$ 150,00');await page.locator('#search').fill('inexistente');await page.getByText('Nenhuma cobrança encontrada.').waitFor();await page.locator('#search').fill('');await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'.preview/dashboard-mobile.png',fullPage:true});

 // Create another invoice and exercise DCC choice, reload, mobile layout and receipt.
 await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:'＋ Nova cobrança'}).click();await page.locator('[name=name]').fill('Doador internacional');await page.locator('[name=amount]').fill('100,00');await page.locator('[name=description]').fill('Doação internacional de demonstração');await page.locator('#create-submit').click();await page.locator('#share-dialog').waitFor({state:'visible'});const foreignUrl=await page.locator('#share-link').inputValue();await donor.goto(foreignUrl);await donor.locator('#demo-foreign').click();await donor.locator('#currency-form').waitFor({state:'visible'});assert.equal(await donor.locator('[name=currency]:checked').count(),0);assert.equal(await donor.locator('[name=currency]').count(),2);await donor.reload();await donor.locator('#currency-form').waitFor({state:'visible'});assert.equal(await donor.locator('[name=currency]:checked').count(),0);assert.equal(await donor.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await donor.screenshot({path:'.preview/currency-mobile.png',fullPage:true});await donor.locator('[name=currency][value=USD]').check();await donor.locator('#confirm-currency').click();await donor.locator('#currency-receipt').waitFor({state:'visible'});assert.match(await donor.locator('#receipt-details').textContent(),/USD/);await donor.reload();await donor.locator('#currency-receipt').waitFor({state:'visible'});await donor.screenshot({path:'.preview/currency-receipt.png',fullPage:true});

 await page.locator('#close-share').click();await page.getByRole('button',{name:'＋ Nova cobrança'}).click();await page.locator('[name=name]').fill('Doador Bitcoin');await page.locator('[name=amount]').fill('100,00');await page.locator('[name=bitcoinAmount]').fill('0.00010000');await page.locator('[name=description]').fill('Doação em Bitcoin');await page.locator('#create-submit').click();await page.locator('#share-dialog').waitFor({state:'visible'});const btcUrl=await page.locator('#share-link').inputValue();await page.locator('#close-share').click();await donor.goto(btcUrl);await donor.locator('#choose-bitcoin').click();await donor.locator('#bitcoin-box').waitFor({state:'visible'});assert.equal(await donor.locator('#bitcoin-qr').isVisible(),false);assert.equal(await donor.locator('#demo-pay').isVisible(),false);await donor.reload();await donor.locator('#bitcoin-box').waitFor({state:'visible'});assert.equal(await donor.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await donor.screenshot({path:'.preview/bitcoin-mobile.png',fullPage:true});await donor.locator('#bitcoin-report-form [name=txid]').fill('a'.repeat(64));await donor.locator('#bitcoin-report-form button').click();await donor.getByText('Transferência informada. A ONG está conferindo o recebimento.').waitFor();await page.locator('#reload').click();await page.getByRole('button',{name:'Conferir Bitcoin'}).click();await page.locator('#bitcoin-confirm-form [name=vout]').fill('0');await page.locator('#bitcoin-confirm-form [name=verified]').check();await page.locator('#bitcoin-confirm-form .primary').click();await page.locator('#bitcoin-dialog').waitFor({state:'hidden'});await donor.reload();await donor.getByText('Doação simulada com sucesso! Nenhuma cobrança foi realizada.').waitFor();

 await page.getByRole('button',{name:'＋ Nova cobrança'}).click();await page.locator('[name=name]').fill('Doador de exemplo');await page.locator('#invoice-currency').selectOption('EUR');await page.locator('[name=amount]').fill('250,00');await page.locator('[name=equivalentBrl]').fill('1500,00');await page.locator('[name=billingAddress]').fill('Rua de exemplo, 10\nLisboa, Portugal');await page.locator('[name=description]').fill('Doação para apoiar as atividades do Instituto Essência Viva.');await page.screenshot({path:'.preview/create-currency.png',fullPage:true});await page.locator('#create-submit').click();await page.locator('#share-dialog').waitFor({state:'visible'});const euroUrl=await page.locator('#share-link').inputValue();const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#download-share').click()]);await download.saveAs('.preview/fatura-eur.pdf');await donor.goto(euroUrl);await donor.getByText('EUR 250,00',{exact:true}).waitFor();assert.match(await donor.locator('#card-equivalent').textContent(),/1.500,00/);assert.equal(await donor.locator('#demo-foreign').isVisible(),false);await donor.screenshot({path:'.preview/invoice-eur-mobile.png',fullPage:true});

 await page.locator('#close-share').click();await page.getByRole('button',{name:'＋ Nova cobrança'}).click();
 await page.locator('[name=name]').fill('Doador com valor ajustável');await page.locator('[name=amount]').fill('100,00');await page.locator('[name=description]').fill('Doação com ajuste autorizado');await page.locator('[name=allowAmountEdit]').check();await page.locator('#create-submit').click();await page.locator('#share-dialog').waitFor({state:'visible'});
 const adjustableUrl=await page.locator('#share-link').inputValue();await donor.goto(adjustableUrl);await donor.locator('#donation-form').waitFor({state:'visible'});assert.equal(await donor.locator('#demo-pay').isDisabled(),true);
 await donor.locator('#donation-currency').selectOption('USD');await donor.waitForFunction(()=>document.querySelector('#donation-value').value==='20,00');await donor.locator('#donation-value').fill('1000,00');await donor.locator('#apply-donation').click();await donor.locator('#donation-confirmation').waitFor({state:'visible'});assert.match(await donor.locator('#donation-confirmation').textContent(),/5.000,00/);
 assert.equal(await donor.locator('#demo-pay').isDisabled(),false);await donor.locator('#donation-value').fill('900,00');assert.equal(await donor.locator('#demo-pay').isDisabled(),true);await donor.locator('#apply-donation').click();await donor.locator('#donation-confirmation').waitFor({state:'visible'});assert.match(await donor.locator('#donation-confirmation').textContent(),/4.500,00/);assert.equal(await donor.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await donor.screenshot({path:'.preview/adjustable-mobile.png',fullPage:true});
 await donor.locator('#demo-pay').click();await donor.getByText('Doação simulada com sucesso! Nenhuma cobrança foi realizada.').waitFor();await donor.reload();assert.equal(await donor.locator('#amount').textContent(),'R$ 100,00');assert.match(await donor.locator('#card-equivalent').textContent(),/4.500,00/);
 const [adjustedPdf]=await Promise.all([donor.waitForEvent('download'),donor.locator('#download-invoice').click()]);await adjustedPdf.saveAs('.preview/fatura-ajustada.pdf');
 await page.locator('#close-share').click();await page.locator('#reload').click();await page.getByText('Cartão: R$ 4.500,00',{exact:true}).waitFor();
 assert.deepEqual(errors,[]);console.log('Fluxo de navegador aprovado: login, criação, link, pagamento demo, persistência, resumo, filtro, telas móveis, escolha de moeda e comprovante.');
} finally {await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));db.close();}
